USE TradePlatform;

DROP TABLE IF EXISTS Product;

CREATE TABLE Product  (
  PID CHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品唯一ID',
  UID CHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用戶唯一ID',
  Name VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品名稱',
  Price INT NOT NULL DEFAULT 0 COMMENT '商品價格',
  ProductStatus TINYINT NOT NULL DEFAULT 0 COMMENT '商品狀態：0為下架(預設)，1為上架，2為完售，3為停售',
  TotalQTY INT NOT NULL DEFAULT 0 COMMENT '商品總數',
  SaleQTY INT NOT NULL DEFAULT 0 COMMENT '商品售出數',
  PhotoURL TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品圖片網址',
  CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  UpdateDate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (PID) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;